apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: avatars-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
  spec:
    containers:
    - name: backend
      image: proyectodevops98/avatars-backend:IMAGE_TAG
      ports:
      - containerPort: 5000  # Puerto de la aplicación
      - containerPort: 8000  # Puerto de métricas
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: avatars-project
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  - protocol: TCP
    port: 8000
    targetPort: 8000

